#!/usr/bin/env python3
"""Generate SHA-512 constants and emit them as a C header.

Never hand-type these. The K table is the first 64 bits of the fractional
parts of the cube roots of the first 80 primes; H is the same for the square
roots of the first 8. Deriving them here removes any risk of a typo, and this
file doubles as an independent check on the kernel.
"""
import math


def primes(n):
    out, c = [], 2
    while len(out) < n:
        if all(c % p for p in out if p * p <= c):
            out.append(c)
        c += 1
    return out


def frac_bits(p, root):
    """First 64 bits of the fractional part of p**(1/root)."""
    one = 1 << 64
    if root == 2:
        whole, scaled = math.isqrt(p), math.isqrt(p << 128)
    else:
        # integer cube root
        x = int(round(p ** (1.0 / 3)))
        while x ** 3 > p:
            x -= 1
        while (x + 1) ** 3 <= p:
            x += 1
        whole = x
        # scaled cube root of p * 2^192
        target = p << 192
        lo, hi = 0, 1 << 90
        while lo < hi:
            mid = (lo + hi + 1) // 2
            if mid ** 3 <= target:
                lo = mid
            else:
                hi = mid - 1
        scaled = lo
    return (scaled - (whole << 64)) & ((1 << 64) - 1)


P = primes(80)
H = [frac_bits(p, 2) for p in P[:8]]
K = [frac_bits(p, 3) for p in P[:80]]

# --- self-check against the published SHA-512 constants ---
KNOWN_H = [0x6A09E667F3BCC908, 0xBB67AE8584CAA73B, 0x3C6EF372FE94F82B, 0xA54FF53A5F1D36F1,
           0x510E527FADE682D1, 0x9B05688C2B3E6C1F, 0x1F83D9ABFB41BD6B, 0x5BE0CD19137E2179]
KNOWN_K0, KNOWN_K79 = 0x428A2F98D728AE22, 0x6C44198C4A475817

assert H == KNOWN_H, f"H mismatch:\n{[hex(x) for x in H]}\n{[hex(x) for x in KNOWN_H]}"
assert K[0] == KNOWN_K0, f"K[0]={hex(K[0])}"
assert K[79] == KNOWN_K79, f"K[79]={hex(K[79])}"
print(f"verified {len(H)} H values and {len(K)} K values against published constants")


def emit_array(name, vals, per_line=4, qualifier="static const"):
    lines = [f"{qualifier} ulong {name}[{len(vals)}] = {{"]
    for i in range(0, len(vals), per_line):
        chunk = ", ".join(f"0x{v:016X}UL" for v in vals[i:i + per_line])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


# host-side header: plain C
with open("sha512_consts.h", "w") as f:
    f.write("/* Generated by gen_consts.py - do not edit by hand. */\n")
    f.write("#ifndef SHA512_CONSTS_H\n#define SHA512_CONSTS_H\n\n")
    f.write(emit_array("SHA512_H0", H) + "\n\n")
    f.write(emit_array("SHA512_K", K) + "\n\n")
    f.write("#endif\n")

# device-side source: program-scope objects must live in __constant
with open("sha512_consts.cl", "w") as f:
    f.write("/* Generated by gen_consts.py - do not edit by hand. */\n\n")
    f.write(emit_array("SHA512_H0", H, qualifier="__constant const") + "\n\n")
    f.write(emit_array("SHA512_K", K, qualifier="__constant const") + "\n")
print("wrote sha512_consts.h (host) and sha512_consts.cl (device)")
