#!/usr/bin/env python3
"""Embed OpenCL kernel sources into the binary for portable builds.

Generates kernels_embed.c with C-escaped copies of the four .cl files plus
a kernels_get(name) lookup. Used only by `make dist`; normal builds keep
loading kernels from disk so the edit/run cycle stays instant.
"""
import sys

FILES = ["sha512_consts.cl", "fe25519.cl", "ge25519.cl", "gpuminer.cl"]


def c_escape(data):
    out = []
    for ch in data:
        o = ord(ch)
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append('\\n"\n"')
        elif 32 <= o < 127:
            out.append(ch)
        else:
            out.append(f"\\{o:03o}")
    return "".join(out)


def main():
    parts = []
    parts.append("/* Generated by gen_embed.py - do not edit by hand. */")
    parts.append("#include <stddef.h>")
    parts.append("#include <string.h>")
    entries = []
    for i, name in enumerate(FILES):
        with open(name, "r") as f:
            src = f.read()
        var = f"kernels_src_{i}"
        parts.append(f'static const char {var}[] =\n"{c_escape(src)}";')
        entries.append(f'    {{"{name}", {var}}},')
    parts.append("static const struct { const char *name; const char *src; } kernels_table[] = {")
    parts.extend(entries)
    parts.append("};")
    parts.append("const char *kernels_get(const char *name) {")
    parts.append("    for (size_t i = 0; i < sizeof(kernels_table)/sizeof(kernels_table[0]); i++)")
    parts.append('        if (strcmp(name, kernels_table[i].name) == 0) return kernels_table[i].src;')
    parts.append("    return 0;")
    parts.append("}")
    with open("kernels_embed.c", "w") as f:
        f.write("\n".join(parts) + "\n")
    print("wrote kernels_embed.c")


if __name__ == "__main__":
    main()
